version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: unicorn_postgres
    environment:
      POSTGRES_USER: annamugu
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: unicorn_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 