services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=unicorn_app
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    networks:
      - unicorn-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=unicorn_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - unicorn-network

volumes:
  postgres_data:

networks:
  unicorn-network:
    driver: bridge 